// components/Level3.tsx
import React, { useState, useEffect, useRef } from 'react';
import { View, TouchableOpacity, Alert, Text } from 'react-native';
import { WebView, WebViewMessageEvent } from 'react-native-webview';

const ASL_SIGNS = {
  'Nice to meet you': 'https://youtu.be/F7Wjb_AIvMA?si=UHE6-gm3HDvyQlRy',
  'And': 'https://youtu.be/PvFguNv1zIk?si=eVUP2W8i4QyT-J1m',
  'Us': 'https://youtu.be/DJU9Vnthfqk?si=p8V4apezjmd16lJI',
  'Need': 'https://www.youtube.com/watch?v=Eo-vEE1gFxM',
  'Thank you': 'https://www.youtube.com/watch?v=IvRwNLNR4_w',
  'Good Morning': 'https://www.youtube.com/watch?v=HWTOUetDsOk',
  'School': 'https://www.youtube.com/watch?v=vuE3RN10AGA',
  'Everyone': 'https://www.youtube.com/watch?v=FFVj-39E94c',
  'Mom': 'https://www.youtube.com/watch?v=DHl2-NT3mIM',
  'Happy': 'https://www.youtube.com/watch?v=ZXHHO_DY6_A',
  'I love you': 'https://www.youtube.com/watch?v=rwBDGMQmmXk',
  'Understand': 'https://www.youtube.com/watch?v=5N10dIavSYc',
  'See you later': 'https://www.youtube.com/watch?v=3n81DT4NTOw',
  'Dad': 'https://www.youtube.com/watch?v=1Vllc4F5ic0',
  'Good job': 'https://www.youtube.com/watch?v=ZyuJALfNGU8',
  'I dont like': 'https://www.youtube.com/watch?v=2zSgd7yskRg',
  'Chocolate': 'https://www.youtube.com/watch?v=pxyi6YW8gOE',
  'Come here please': 'https://www.youtube.com/watch?v=UlBU161E6pY',
  'Allow': 'https://www.youtube.com/watch?v=w705jpxY8m8',
  'Food is good': 'https://www.youtube.com/watch?v=JbNaGbl_7lM',
  'Pen?': 'https://www.youtube.com/watch?v=1JySi0OYMcc',
  'Trick or Treat?': 'https://www.youtube.com/watch?v=MwxlbFYyLhw',
  'I am sorry': 'https://www.youtube.com/watch?v=imDas8UGjv4',
  'Where do you live?': 'https://www.youtube.com/watch?v=NOpWKcox14o',
  'Texas': 'https://www.youtube.com/watch?v=YMdSm_OgAIo',
  'I am deaf': 'https://youtu.be/0S8dgbKhxpA?si=4HKDcx-yZoUde9g7'
};

const Level3Screen: React.FC = () => {
  const [currentQuestion, setCurrentQuestion] = useState<string>('');
  const [options, setOptions] = useState<string[]>([]);
  const [health, setHealth] = useState<number>(1);
  const [currentVideoUrl, setCurrentVideoUrl] = useState<string>('');
  const webViewRef = useRef<WebView>(null);

  useEffect(() => {
    newQuestion();
  }, []);

  const newQuestion = () => {
    const signs = Object.keys(ASL_SIGNS);
    const correctAnswer = signs[Math.floor(Math.random() * signs.length)];
    setCurrentQuestion(correctAnswer);
    setCurrentVideoUrl(ASL_SIGNS[correctAnswer as keyof typeof ASL_SIGNS]);

    let wrongAnswers = signs.filter(sign => sign !== correctAnswer);
    wrongAnswers = wrongAnswers.sort(() => 0.5 - Math.random()).slice(0, 3);

    const allOptions = [correctAnswer, ...wrongAnswers].sort(() => 0.5 - Math.random());
    setOptions(allOptions);
  };

  const handleAnswer = (selectedAnswer: string) => {
    if (selectedAnswer === currentQuestion) {
      setHealth(Math.min(1, health + 0.1));
      Alert.alert('Correct!', 'Great job!', [{ text: 'Next', onPress: () => newQuestion() }]);
    } else {
      setHealth(Math.max(0, health - 0.2));
      Alert.alert('Incorrect', `The correct answer was ${currentQuestion}. Try again!`, [
        { text: 'Next', onPress: () => newQuestion() }
      ]);
    }
  };

  const getHealthColor = () => {
    if (health > 0.6) return 'bg-green-500';
    if (health > 0.3) return 'bg-yellow-500';
    return 'bg-red-500';
  };

  const replayVideo = () => {
    if (webViewRef.current) {
      webViewRef.current.injectJavaScript(`
        var video = document.querySelector('video');
        if (video) {
          video.currentTime = 0;
          video.play();
        }
        true;
      `);
    }
  };

  return (
    <View className='flex-1 justify-center items-center bg-gray-100 p-4'>
      <View className='bg-white rounded-lg shadow-md p-6 w-full max-w-md'>
        <Text className='text-2xl font-bold text-center mb-4'>ASL Learning</Text>
        <View className='w-full h-5 bg-gray-200 rounded-full mb-2'>
          <View className={`h-full rounded-full ${getHealthColor()}`} style={{ width: `${health * 100}%` }} />
        </View>
        <Text className='text-center text-lg font-semibold mb-4'>{`Health: ${Math.round(health * 100)}%`}</Text>
        
        <Text className='text-center text-lg font-semibold mb-2'>What sign is this?</Text>
        <WebView 
          ref={webViewRef}
          source={{ uri: currentVideoUrl }} 
          style={{ height: 200, marginBottom: 16 }} 
        />
        
        <TouchableOpacity
          onPress={replayVideo}
          className='bg-red-500 rounded-lg p-2 mb-4 self-center'
        >
          <Text className='text-white text-center font-bold px-2'>Play Again</Text>
        </TouchableOpacity>

        <View className='flex-row flex-wrap justify-center'>
          {options.map((option, index) => (
            <TouchableOpacity
              key={index}
              onPress={() => handleAnswer(option)}
              className='bg-blue-500 rounded-lg p-2 mb-4 mx-2' // Added horizontal margin
            >
              <Text className='text-white text-center font-bold px-2'>{option}</Text>
            </TouchableOpacity>
          ))}
        </View>
      </View>
    </View>
  );
};

export default Level3Screen;

// src/Level3.svelte
<script>
  import { createEventDispatcher, onMount } from 'svelte';
  
  const dispatch = createEventDispatcher();

  let currentQuestion = '';
  let options = [];
  let health = 1;
  let currentVideoPath = '';
  let videoElement;

  const ASL_SIGNS = {
    'Nice to meet you': 'Nicetomeetyou.mp4',
    'And': 'And.mp4',
    'Us': 'Us.mp4',
    'Need': 'Need.mp4',
    'Thank you': 'Thankyou.mp4',
    'Good Morning': 'Goodmorning.mp4',
    'School': 'School.mp4',
    'Everyone': 'Everyone.mp4',
    'Mom': 'Mom.mp4',
    'Happy': 'Happy.mp4',
    'I love you': 'Iloveyou.mp4',
    'Understand': 'Understand.mp4',
    'See you later': 'Seeyoulater.mp4',
    'Dad': 'Dad.mp4',
    'Good job': 'Goodjob.mp4',
    "I don't like": "Idontlike.mp4",
    'Chocolate': 'Chocolate.mp4',
    'Come here please': 'Comehereplease.mp4',
    'Allow': 'Allow.mp4',
    'Food is good': 'Foodisgood.mp4',
    'Pen?': 'Pen.mp4',
    'Trick or Treat?': 'Trickortreat.mp4',
    'I am sorry': 'Iamsorry.mp4',
    'Where do you live?': 'Wheredoyoulive.mp4',
    'Texas': 'Texas.mp4',
    'I am deaf': 'Iamdeaf.mp4'
  };

  function newQuestion() {
    const phrases = Object.keys(ASL_SIGNS);
    currentQuestion = phrases[Math.floor(Math.random() * phrases.length)];
    currentVideoPath = `level3videos/${ASL_SIGNS[currentQuestion]}`;
    console.log('Current video path:', currentVideoPath); // Log the path for debugging
    let wrongAnswers = phrases.filter(phrase => phrase !== currentQuestion);
    wrongAnswers = wrongAnswers.sort(() => 0.5 - Math.random()).slice(0, 3);
    options = [currentQuestion, ...wrongAnswers].sort(() => 0.5 - Math.random());
    loadAndPlayVideo();
  }

  function loadAndPlayVideo() {
    if (videoElement) {
      videoElement.load();
    }
  }

  function handleAnswer(selectedAnswer) {
    if (selectedAnswer === currentQuestion) {
      health = Math.min(1, health + 0.1);
      alert('Correct! Great job!');
    } else {
      health = Math.max(0, health - 0.2);
      alert(`Incorrect. The correct answer was "${currentQuestion}". Try again!`);
    }
    newQuestion();
  }

  function getHealthColor() {
    if (health > 0.6) return 'bg-green-500';
    if (health > 0.3) return 'bg-yellow-500';
    return 'bg-red-500';
  }

  function replayVideo() {
    if (videoElement) {
      videoElement.currentTime = 0;
      videoElement.play();
    }
  }

  onMount(() => {
    newQuestion();
  });
</script>

<div class="level3">
  <h1>ASL Phrases Learning</h1>
  <div class="health-bar">
    <div class={getHealthColor()} style="width: {health * 100}%"></div>
  </div>
  <p>Health: {Math.round(health * 100)}%</p>
  <p>What phrase is being signed?</p>
  <video bind:this={videoElement} src={currentVideoPath} controls muted width="560" height="315"></video>
  <button class="replay_button" on:click={replayVideo}>Replay Video</button>
  <div class="options">
    {#each options as option}
      <button on:click={() => handleAnswer(option)}>{option}</button>
    {/each}
  </div>
  <button on:click={() => dispatch('back')}>Back to Lessons</button>
</div>

<style>
  .level3 {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .health-bar {
    width: 100%;
    height: 20px;
    background-color: #e0e0e0;
    border-radius: 10px;
    overflow: hidden;
    margin-bottom: 10px;
  }

  .health-bar div {
    height: 100%;
    transition: width 0.3s ease-in-out;
  }

  .bg-green-500 { background-color: #48bb78; }
  .bg-yellow-500 { background-color: #ecc94b; }
  .bg-red-500 { background-color: #f56565; }

  .options {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 10px;
    margin-bottom: 20px;
  }

  button {
    background-color: #4299e1;
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 5px;
    cursor: pointer;
    font-size: 1em;
    margin: 10px 0;
  }
  .replay_button {
    background-color: #ff0000;
  }
</style>
